defmodule App.Users.BankList do
  @moduledoc """
  This module contains list of banks that are supported by Midtrans.
  https://docs.midtrans.com/reference/list-of-supported-banks
  """
  @enabled_banks ["bca", "bni", "bri", "danamon", "mandiri", "permata"]
  @banks [
    {"aceh", "BANK ACEH"},
    {"aceh_syar", "BPD ISTIMEWA ACEH SYARIAH"},
    {"agris", "BANK AGRIS"},
    {"agroniaga", "BANK RAKYAT INDONESIA AGRONIAGA"},
    {"allo", "ALLO BANK INDONESIA"},
    {"amar", "BANK AMAR INDONESIA"},
    {"andara", "BANK ANDARA"},
    {"anglomas", "ANGLOMAS INTERNATIONAL BANK"},
    {"antar_daerah", "BANK ANTAR DAERAH"},
    {"anz", "BANK ANZ INDONESIA"},
    {"artajasa", "ARTAJASA"},
    {"artha", "BANK ARTHA GRAHA INTERNASIONAL"},
    {"bali", "BANK PEMBANGUNAN DAERAH BALI"},
    {"bangkok", "BANGKOK BANK PUBLIC"},
    {"banten", "BANK BANTEN"},
    {"barclays", "BANK BARCLAYS INDONESIA"},
    {"bca", "BANK CENTRAL ASIA"},
    {"bcad", "BANK DIGITAL BCA"},
    {"bca_syar", "BANK BCA SYARIAH"},
    {"bengkulu", "BPD BENGKULU"},
    {"bisnis", "BANK BISNIS INTERNASIONAL"},
    {"bjb", "BANK PEMBANGUNAN DAERAH JABAR DAN BANTEN"},
    {"bjb_syar", "BANK JABAR BANTEN SYARIAH"},
    {"bni", "BANK NEGARA INDONESIA"},
    {"bnp", "BANK NUSANTARA PARAHYANGAN"},
    {"bnp_paribas", "BANK BNP PARIBAS INDONESIA"},
    {"boa", "BANK OF AMERICA NA"},
    {"bri", "BANK RAKYAT INDONESIA"},
    {"bsi", "BANK SYARIAH INDONESIA"},
    {"btn", "BANK TABUNGAN NEGARA"},
    {"btn_syar", "BANK TABUNGAN NEGARA - UNIT USAHA SYARIAH"},
    {"btpn", "BANK BTPN"},
    {"btpn_syar", "BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH"},
    {"bukopin", "BANK KB BUKOPIN"},
    {"bukopin_syar", "BANK SYARIAH BUKOPIN"},
    {"bumiputera", "BANK BUMIPUTERA"},
    {"bumi_artha", "BANK BUMI ARTA"},
    {"capital", "BANK CAPITAL INDONESIA"},
    {"centratama", "CENTRATAMA NASIONAL BANK"},
    {"chase", "JP MORGAN CHASE BANK, N.A"},
    {"china", "BANK OF CHINA"},
    {"china_cons", "CHINA CONSTRUCTION"},
    {"chinatrust", "BANK CTBC INDONESIA"},
    {"cimb", "BANK CIMB NIAGA"},
    {"cimb_syar", "BANK CIMB NIAGA - UNIT USAHA SYARIAH"},
    {"cimb_rekening_ponsel", "BANK CIMB NIAGA - REKENING PONSEL"},
    {"cimb_va", "BANK CIMB NIAGA - VIRTUAL ACCOUNT"},
    {"citibank", "CITIBANK, NA"},
    {"commonwealth", "BANK COMMONWEALTH"},
    {"danamon", "BANK DANAMON INDONESIA"},
    {"danamon_syar", "BANK DANAMON INDONESIA - UNIT USAHA SYARIAH"},
    {"dbs", "BANK DBS INDONESIA"},
    {"deutsche", "DEUTSCHE BANK AG."},
    {"dipo", "BANK DIPO INTERNATIONAL"},
    {"diy", "BANK PEMBANGUNAN DAERAH DIY"},
    {"diy_syar", "BANK PEMBANGUNAN DAERAH DIY - UNIT USAHA SYARIAH"},
    {"dki", "BANK DKI"},
    {"dki_syar", "BANK DKI - UNIT USAHA SYARIAH"},
    {"ekonomi", "BANK EKONOMI RAHARJA"},
    {"fama", "BANK FAMA INTERNATIONAL"},
    {"ganesha", "BANK GANESHA"},
    {"gopay", "GO-PAY"},
    {"hana", "BANK KEB HANA INDONESIA"},
    {"hs_1906", "BANK HS 1906"},
    {"hsbc", "BANK HSBC INDONESIA"},
    {"icbc", "BANK ICBC INDONESIA"},
    {"ina_perdana", "BANK INA PERDANA"},
    {"index_selindo", "BANK INDEX SELINDO"},
    {"india", "BANK OF INDIA INDONESIA"},
    {"jago", "BANK JAGO"},
    {"jago_syar", "BANK JAGO - UNIT USAHA SYARIAH"},
    {"jambi", "BANK PEMBANGUNAN DAERAH JAMBI"},
    {"jasa_jakarta", "BANK JASA JAKARTA"},
    {"jateng", "BANK PEMBANGUNAN DAERAH JAWA TENGAH"},
    {"jateng_syar", "BANK PEMBANGUNAN DAERAH JAWA TENGAH"},
    {"jatim", "BANK PEMBANGUNAN DAERAH JATIM"},
    {"jatim_syar", "BANK PEMBANGUNAN DAERAH JATIM - UNIT USAHA SYARIAH"},
    {"jtrust", "BANK JTRUST INDONESIA"},
    {"kalbar", "BANK PEMBANGUNAN DAERAH KALBAR"},
    {"kalbar_syar", "BANK PEMBANGUNAN DAERAH KALBAR UUS"},
    {"kalsel", "BANK PEMBANGUNAN DAERAH KALSEL"},
    {"kalsel_syar", "BANK PEMBANGUNAN DAERAH KALSEL - UNIT USAHA SYARIAH"},
    {"kalteng", "BPD KALIMANTAN TENGAH"},
    {"kaltim", "BANK PEMBANGUNAN DAERAH KALTIM"},
    {"kaltim_syar", "BANK PEMBANGUNAN DAERAH KALTIM - UNIT USAHA SYARIAH"},
    {"lampung", "BANK PEMBANGUNAN DAERAH LAMPUNG"},
    {"maluku", "BANK PEMBANGUNAN DAERAH MALUKU"},
    {"mandiri", "BANK MANDIRI"},
    {"mandiri_taspen", "BANK MANDIRI TASPEN POS"},
    {"maspion", "BANK MASPION"},
    {"mayapada", "BANK MAYAPADA"},
    {"maybank", "BANK MAYBANK INDONESIA"},
    {"maybank_syar", "BANK MAYBANK SYARIAH INDONESIA"},
    {"maybank_uus", "BANK MAYBANK INDONESIA - UNIT USAHA SYARIAH"},
    {"mayora", "BANK MAYORA"},
    {"mega_syar", "BANK MEGA SYARIAH"},
    {"mega_tbk", "BANK MEGA"},
    {"mestika", "BANK MESTIKA DHARMA"},
    {"metro", "BANK METRO EXPRESS"},
    {"mitraniaga", "BANK MITRANIAGA"},
    {"mitsubishi", "THE BANK OF TOKYO MITSUBISHI UFJ LTD."},
    {"mizuho", "BANK MIZUHO INDONESIA"},
    {"mnc", "BANK MNC INTERNASIONAL"},
    {"muamalat", "BANK MUAMALAT INDONESIA"},
    {"multiarta", "BANK MULTI ARTA SENTOSA"},
    {"mutiara", "BANK MUTIARA"},
    {"niaga_syar", "BANK NIAGA SYARIAH"},
    {"nagari", "BANK NAGARI"},
    {"nobu", "BANK NATIONALNOBU"},
    {"ntb", "BANK PEMBANGUNAN DAERAH NTB"},
    {"ntt", "BANK PEMBANGUNAN DAERAH NTT"},
    {"ocbc", "BANK OCBC NISP"},
    {"ocbc_syar", "BANK OCBC NISP - UNIT USAHA SYARIAH"},
    {"ok", "BANK OKE INDONESIA"},
    {"ovo", "OVO"},
    {"panin", "PANIN BANK"},
    {"panin_syar", "BANK PANIN SYARIAH"},
    {"papua", "BANK PEMBANGUNAN DAERAH PAPUA"},
    {"permata", "BANK PERMATA"},
    {"permata_syar", "BANK PERMATA - UNIT USAHA SYARIAH"},
    {"permata_va", "BANK PERMATA - VIRTUAL ACCOUNT"},
    {"prima_master", "PRIMA MASTER BANK"},
    {"pundi", "BANK PUNDI INDONESIA"},
    {"purba", "BANK PURBA DANARTA"},
    {"qnb", "BANK QNB INDONESIA"},
    {"rabobank", "BANK RABOBANK INTERNATIONAL INDONESIA"},
    {"rbos", "THE ROYAL BANK OF SCOTLAND N.V."},
    {"resona", "BANK RESONA PERDANIA"},
    {"riau", "BANK PEMBANGUNAN DAERAH RIAU KEPRI"},
    {"riau_syar", "BANK PEMBANGUNAN DAERAH RIAU KEPRI SYARIAH"},
    {"sampoerna", "BANK SAHABAT SAMPOERNA"},
    {"sbi", "BANK SBI INDONESIA"},
    {"seabank", "BANK SEABANK INDONESIA"},
    {"shinhan", "BANK SHINHAN INDONESIA"},
    {"sinarmas", "BANK SINARMAS"},
    {"sinarmas_syar", "BANK SINARMAS - UNIT USAHA SYARIAH"},
    {"stanchard", "STANDARD CHARTERED BANK"},
    {"sulselbar", "BANK SULSELBAR"},
    {"sulselbar_syar", "BANK SULSELBAR - UNIT USAHA SYARIAH"},
    {"sulteng", "BPD SULAWESI TENGAH"},
    {"sultenggara", "BPD SULAWESI TENGGARA"},
    {"sulut", "BANK SULUTGO"},
    {"sumbar", "BPD SUMATERA BARAT"},
    {"sumitomo", "BANK SUMITOMO MITSUI INDONESIA"},
    {"sumsel_babel", "BPD SUMSEL DAN BABEL"},
    {"sumsel_babel_syar", "BPD SUMSEL DAN BABEL - UNIT USAHA SYARIAH"},
    {"sumut", "BANK PEMBANGUNAN DAERAH SUMUT"},
    {"sumut_syar", "BANK PEMBANGUNAN DAERAH SUMUT UUS"},
    {"uob", "BANK UOB INDONESIA"},
    {"victoria", "BANK VICTORIA INTERNATIONAL"},
    {"victoria_syar", "BANK VICTORIA SYARIAH"},
    {"woori", "BANK WOORI SAUDARA INDONESIA 1906"},
    {"yudha_bhakti", "BANK YUDHA BHAKTI"}
  ]

  def all do
    @banks
  end

  def enabled do
    Enum.filter(@banks, fn {code, _} -> Enum.member?(@enabled_banks, code) end)
  end
end
